name: minha_cidade
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  chopper: ^5.1.0
  injectable: ^1.5.4
  get_it: ^7.2.0
  auto_route: ^5.0.2
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  bloc: ^8.1.0
  json_serializable: ^6.5.4
  connectivity_plus: ^0.0.1
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  map_launcher: ^2.4.0
  flutter_form_builder: ^7.7.0
  location: ^2.5.4
  camera: ^0.9.3+1
  image_picker: ^0.7.2+1
  map: ^1.3.4
  latlng: ^0.2.0
  pull_to_refresh: ^2.0.0
  http: ^0.13.5
  flutter_login: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  chopper_generator: ^5.1.0+1
  injectable_generator: ^1.5.5
  auto_route_generator: ^5.0.3
  freezed: ^2.2.1
  flutter_gen_runner: ^5.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/

flutter_gen:
  output: lib/generated
  line_length: 80
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml

flutter_intl:
  enabled: true
  class_name: S
  main_locale: pt
  arb_dir: assets/l10n
  output_dir: lib/generated